### ISSUE TITLE
Join forces

### ISSUE THREAD

**Issue by jchannon** [jinmingjian/sde#25]
Hi I'd love to see propert Swift support and debugging, intellisense etc come to VSCode.

There seems to be considerable effort from you and the chap here https://github.com/RLovelett/vscode-swift , I think he's writing a VSCode Language Server protocol so he can work with VSCode more tighly.  Why not join forces and make Swift in VSCode a great thing?

Just an idea 😄

**Comment by jinmingjian** [comment]
@jchannon  thanks for your idea. I have investigated the RL's project before I started. I originally hope to do some contributions if I can. The result is that I can not be joyful to make any addons in current "framework". Even this is a free game, I hope to do my best as possible.

Most reasons I have mentioned in the REAMDME and issue #9. The main work of this project are done in Nov. to Dec. of 2016, before which I even have not touched the typescript.  As you can see, the work could be done much faster, if we do the engineering in a right way. 

In fact, now I've implemented a __more complete LS server__  in this project than that of RL's project. So, it is more rationale to contribute to this SDE project for us. But I seem not feasible/appropriate to ask this cooperation because I am the author of the SDE? :worried:

**Comment by jchannon** [comment]
Ah good to know yours is more complete.

I spent a lot of time looking at Swift and the Vapor web fwk, then came to
a point to use it and couldn't stand XCode.  Jetbrains AppCode didn't do
server side Swift so gave up.  Maybe I'll try your plugin etc and see how I
get on!

Good job on the work!

**Comment by jinmingjian** [comment]
@jchannon very nice to hear that you have interested in this project. I am preparing a new release. But I am just out from the vacation of Chinese new year. There is a problem for new LS backend linking in macOS which I have no enough time to focus on before. I still hope to release it in one or two day.

Idea and suggest are always welcome! :smile:
